language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - python -m pytest
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true