language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

before_install:
  - pip install poetry
install:
  - poetry install

script:
  - python -m pytest

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PW
  - poetry build -f sdist
deploy:
  provider: script
  script: poetry publish
  skip_existing: true
  on:
    tags: true