name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package manager
        run: pip install poetry poetry-dynamic-versioning

      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run python -m pytest --cov=pydelegate --cov-report=term
